# Generated by Django 4.2.16 on 2024-11-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_unit', models.TextField()),
                ('cur_nm', models.TextField()),
                ('deal_bas_r', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
