# Generated by Django 4.2.16 on 2024-11-23 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('piggy_banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piggybank',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piggy_bank', to=settings.AUTH_USER_MODEL),
        ),
    ]
