# Generated by Django 4.2.16 on 2024-11-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggy_banks', '0002_alter_piggybank_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='piggybank',
            name='saving_purpose',
            field=models.TextField(default='home'),
            preserve_default=False,
        ),
    ]
