# Generated by Django 4.2.16 on 2024-11-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
        ('bank_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_bank_products',
            field=models.ManyToManyField(related_name='bank_product_users', to='bank_products.bankproducts'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
