# Generated by Django 4.2.16 on 2024-11-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
                ('company_code', models.TextField()),
                ('company_name', models.TextField()),
                ('product_code', models.TextField()),
                ('product_name', models.TextField()),
                ('interest_rate', models.FloatField()),
                ('prime_interest_rate', models.FloatField()),
                ('product_link', models.TextField()),
                ('join_period', models.TextField()),
                ('join_period_text', models.TextField()),
                ('join_amount_min', models.IntegerField()),
                ('join_amount_max', models.IntegerField(null=True)),
                ('join_amount_text', models.TextField()),
                ('join_way', models.TextField(null=True)),
                ('join_member', models.TextField()),
                ('prime_conditions', models.TextField(null=True)),
                ('interest_payment', models.TextField(null=True)),
                ('note', models.TextField(null=True)),
            ],
        ),
    ]
