# Generated by Django 4.2.16 on 2024-11-18 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('join_period', models.IntegerField()),
                ('monthly_amount', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_bank_products', models.ManyToManyField(related_name='bank_product_users', to='bank_products.bankproducts')),
            ],
        ),
    ]
